services:
  nginx:
    image: nginx:1.27-alpine
    restart: always
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./nginx/:/etc/nginx/conf.d

    ports:
      - '8000:80'
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - web

  web:
    image: &image shalom_enterprise
    build: .
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    restart: always
    command: [ "uvicorn", "--host", "0.0.0.0", "--port", "8000", "--workers", "2", "--log-level", "info", "shalom_enterprise.asgi:application" ]
    volumes: &volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - ./static:/code/static
      - ./media:/code/media
    env_file: &env_file ./.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    command: postgres -N 568
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shalom_afric
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/



  migration:
    image: *image
    env_file: *env_file
    command: /bin/sh -c 'python manage.py migrate && python manage.py collectstatic --noinput && python manage.py seed_db'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    volumes: *volumes
    depends_on:
      - db

 

volumes:
  postgres_data:
  redis_data: