version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "./wait-for-db.sh &&
              python manage.py collectstatic --noinput &&
              python manage.py migrate &&
              gunicorn --bind 0.0.0.0:8000 --workers 2 --threads 2 --timeout 120 shalom_enterprise.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DB_NAME=shalom_afric
      - DB_USER=kelvin
      - DB_PASSWORD=kelvin
      - DB_HOST=db
      - DB_PORT=5432
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_fin_timeout=30
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

    networks:
      app-network:
        aliases:
          - web
          - webserver  # Add additional aliases if needed

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shalom_afric
      - POSTGRES_USER=kelvin
      - POSTGRES_PASSWORD=kelvin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kelvin -d shalom_afric"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge