# Generated by Django 4.2.20 on 2025-06-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('changed_mind', 'Changed my mind'), ('found_cheaper', 'Found cheaper elsewhere'), ('shipping_time', 'Shipping takes too long'), ('other', 'Other reason')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
