# Generated by Django 4.2.20 on 2025-06-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_cancellation_notes_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
