"""
Django settings for shalom_enterprise project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-06sxf-rs^o_kplj1k-m@2ji%9f#8d45*usxhxdnl3s4%1di@2q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['165.227.85.34','localhost','127.0.0.1','www.google.com','saexpress.store','www.saexpress.store']


# Applicatio  "http://165.227.85.34",
INSTALLED_APPS = [
       "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "django.contrib.admin",  # required
 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'authentication',
    "shalom_enterprise",
    "products",
    'rest_framework',
    'corsheaders',
    'cart',
    'checkout',
    'settings',
  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
      'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'shalom_enterprise.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'shalom_enterprise.context_processors.global_data',
                'django.contrib.messages.context_processors.messages',               
            ],
        },
    },
]

WSGI_APPLICATION = 'shalom_enterprise.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST"),
            "PORT": int(os.getenv("POSTGRES_PORT", 5432)),
            "OPTIONS": {"sslmode": os.getenv("PGSSLMODE", "prefer")},
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),  # if you have additional static directories
]

# Media files (user uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# settings.py
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "authentication.CustomUser"
#



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587  # Port for SSL (not TLS)
EMAIL_USE_SSL = False  # Must be True for port 465
EMAIL_USE_TLS = True # Must be False if SSL is True
EMAIL_HOST_USER = os.getenv("EMAIL")  # Your full Zoho email (e.g., user@domain.com)
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")  # Your Zoho password or App Password (if 2FA enabled)
DEFAULT_FROM_EMAIL = "enterpriseshalom676@gmail.com"  # Must match EMAIL_HOST_USER


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}



CORS_ALLOWED_ORIGINS = [
    "http://localhost",  # Your frontend URL
    "http://127.0.0.10",
    "http://0.0.0.0",
    "https://shalom-enterprise-1.onrender.com"
    'shalom-enterprise-1.onrender.com',
      "http://165.227.85.34",
    "https://165.227.85.34",
     'https://www.google.com',
        'https://saexpress.store',
         "http://www.saexpress.store",
         'http://saexpress.store',
         
    ]

CORS_ALLOW_CREDENTIALS = True  # To allow cookies


CSRF_TRUSTED_ORIGINS = [
     "https://www.saexpress.store",
    # Add other trusted origins if needed
    'http://127.0.0.1',
    "http://127.0.0.1:8000",
    'http://localhost',
    'http://0.0.0.0',
      "http://165.227.85.34",
    "https://165.227.85.34",
    'https://www.google.com'
    'http://saexpress.store',
    "http://www.saexpress.store/",
    'https://saexpress.store',
    
    

]

UNFOLD = {
    "SITE_TITLE": "Shalom Afric Enterprise",
    "SITE_HEADER": "Shalom Afric Enterprise",
    "DASHBOARD_CALLBACK": "shalom_enterprise.dashboard.dashboard_callback",
    
    "SITE_ICON": {
        "light": "/static/img/image.png",
        "dark": "/static/img/image.png",
    },
    "DARK_MODE": True,
    "LOGIN": {
        "image": "/static/img/hotdeal.png",
        "title": "Welcome to Shalom Afric Enterprise Admin Portal",
        "description": "Please enter your credentials",
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
    },
    "TEMPLATES": {
        "DASHBOARD": "admin/dashboard.html",
    },
}
ZOHO_CLIENT_ID = os.getenv('ZOHO_CLIENT_ID')
ZOHO_CLIENT_SECRET = os.getenv('ZOHO_CLIENT_SECRET')