# Generated by Django 4.2.20 on 2025-06-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='region',
        ),
    ]
