# Generated by Django 4.2.20 on 2025-06-04 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productreview_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (e.g., 20 for 20% off)', max_digits=5, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated current price', max_digits=10, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed special price (overrides percentage discount)', max_digits=10, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the deal should become active')),
                ('end_date', models.DateTimeField(help_text='When the deal should expire')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle deal on/off')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_deals', to='products.product')),
            ],
            options={
                'verbose_name': 'Hot Deal',
                'verbose_name_plural': 'Hot Deals',
                'ordering': ['-start_date'],
            },
        ),
    ]
