# Generated by Django 4.2.20 on 2025-07-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_hotdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_used',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
