# Generated by Django 4.2.20 on 2025-07-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cart_price_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_count', models.PositiveIntegerField(default=0, help_text='Total number of times this product has been sold')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product should be displayed as a top seller')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_seller', to='products.product')),
            ],
            options={
                'verbose_name': 'Top Seller',
                'verbose_name_plural': 'Top Sellers',
                'ordering': ['-sales_count'],
            },
        ),
    ]
