# Generated by Django 4.2.20 on 2025-07-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_topseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topseller',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topseller', to='products.product'),
        ),
    ]
